# Deployment for Nginx pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment1
  labels:
    app: nginx-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx-container-2
        image: asia-south2-docker.pkg.dev/pnb-prod/dr-pnb-bou/dr-pnb-bou-dashboard:production-c8fa530
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"         # Minimum 0.1 CPU core
            memory: "128Mi"     # Minimum 128 MB memory
          limits:
            cpu: "500m"         # Maximum 0.5 CPU core
            memory: "512Mi"     # Maximum 512 MB memory
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service1
  namespace: default
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: nginx-pod
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80 # Match containerPort in the Deployment
  selector:
    app: nginx-pod # Match Deployment labels
  externalTrafficPolicy: Cluster
